--!strict

local RunItems = {}

RunItems.Ids = {
	FuseBomb = "fuse_bomb",
	SilverNinjaStarOfTheBrilliantLight = "silver_ninja_star_of_the_brilliant_light",
	HistoricTimmyGun = "historic_timmy_gun",
	TeddyBloxpin = "teddy_bloxpin",
	RegenerationCoil = "regeneration_coil",
	HealingPotion = "healing_potion",
	LaserElectrocutor = "laser_electrocutor",
	BuildersClubHardHat = "builders_club_hard_hat",
	PepperoniPizza = "pepperoni_pizza",
	DeleteTool = "delete_tool",
	AduriteCape = "adurite_cape",
	SpeedCoil = "speed_coil",
	BloxyCola = "bloxy_cola",
	Cheezburger = "cheezburger",
	Bloxiade = "bloxiade",
	Cake = "cake",
	EnergySword = "energy_sword",
	Magic8Ball = "magic_8_ball",
	Apple = "apple",
}

RunItems.Order = {
	RunItems.Ids.FuseBomb,
	RunItems.Ids.SilverNinjaStarOfTheBrilliantLight,
	RunItems.Ids.HistoricTimmyGun,
	RunItems.Ids.TeddyBloxpin,
	RunItems.Ids.RegenerationCoil,
	RunItems.Ids.HealingPotion,
	RunItems.Ids.LaserElectrocutor,
	RunItems.Ids.BuildersClubHardHat,
	RunItems.Ids.PepperoniPizza,
	RunItems.Ids.DeleteTool,
	RunItems.Ids.AduriteCape,
	RunItems.Ids.SpeedCoil,
	RunItems.Ids.BloxyCola,
	RunItems.Ids.Cheezburger,
	RunItems.Ids.Bloxiade,
	RunItems.Ids.Cake,
	RunItems.Ids.EnergySword,
	RunItems.Ids.Magic8Ball,
	RunItems.Ids.Apple,
}

RunItems.DefaultDropSettings = {
	requiresInteract = true,
	interactionRadius = 20,
	autoPickupRadius = 5.0,
	spinPeriod = 8.0,
	bobAmplitude = 0.2,
	noDespawn = true,
	forwardDistance = 5.0,
	groundLift = 1.25,
}

RunItems.Definitions = {
	[RunItems.Ids.FuseBomb] = {
		id = RunItems.Ids.FuseBomb,
		entryId = "item:" .. RunItems.Ids.FuseBomb,
		displayName = "Fuse Bomb",
		description = "Gain a 30% (+20% per stack) chance to drop a bomb upon taking damage. This bomb detonates after 2 seconds, dealing 1000% (+800% per stack) base damage, on a 15 (-35% per stack) second cooldown.",
		promptDescription = [[Gain a 30% <font color="#7A7A7A">(+20% per stack)</font> chance to drop a <font color="#F4A11A">bomb</font> upon <font color="#17E317">taking damage</font>. This bomb detonates after 2 seconds, dealing <font color="#F4A11A">1000%</font> <font color="#7A7A7A">(+800% per stack)</font> <font color="#F4A11A">base damage</font>, on a 15 <font color="#7A7A7A">(-35% per stack)</font> second cooldown.]],
		dropModelName = "Fuse Bomb",
		viewportFrameName = "FuseBombImageLabel",
		worldDropVisual = {
			renderMode = "legacySpecialMeshBackface",
			preferredChildName = "Fuse Bomb",
		},
		fuseBomb = {
			baseProcChance = 0.30,
			stackProcChance = 0.20,
			baseCooldown = 15.0,
			stackCooldownMultiplier = 0.65,
			detonationDelay = 2.0,
			baseDamageCoefficient = 10.0,
			stackDamageCoefficient = 8.0,
			explosionSize = Vector3.new(50, 50, 50),
			explosionRadius = 25.0,
		},
	},
	[RunItems.Ids.SilverNinjaStarOfTheBrilliantLight] = {
		id = RunItems.Ids.SilverNinjaStarOfTheBrilliantLight,
		entryId = "item:" .. RunItems.Ids.SilverNinjaStarOfTheBrilliantLight,
		displayName = "Silver Ninja Star of the Brilliant Light",
		description = "Attacks follow up with a tracking ninja star, dealing 450% (+350% per stack) base damage, with 3 (+2 per stack) charges, and a 15 second cooldown.",
		promptDescription = [[<font color="#F4A11A">Attacks</font> follow up with a tracking <font color="#F4A11A">ninja star</font>, dealing <font color="#F4A11A">450%</font> <font color="#7A7A7A">(+350% per stack)</font> <font color="#F4A11A">base damage</font>, with <font color="#4A86FF">3</font> <font color="#7A7A7A">(+2 per stack)</font> <font color="#4A86FF">charges</font>, and a 15 second cooldown.]],
		dropModelName = "Silver Ninja Star of the Brilliant Light",
		viewportFrameName = "SilverNinjaStaroftheBrilliantLightImageLabel",
		worldDropVisual = {
			renderMode = "preferredDescendant",
		},
		silverStar = {
			baseDamageCoefficient = 4.5,
			stackDamageCoefficient = 3.5,
			baseCharges = 3,
			chargesPerStack = 2,
			rechargeDuration = 15.0,
			projectileSpeed = 100.0,
			projectileLifetime = 4.0,
			hitboxSize = Vector3.new(5, 5, 5),
			hitboxRadius = 2.5,
			homing = {
				acquireRadius = 100.0,
				strengthDeg = 40.0,
				maxAngleDeg = 150.0,
				maxTurnDeg = 40.0,
				stayHorizontal = false,
				alwaysStayHorizontal = false,
			},
		},
	},
	[RunItems.Ids.HistoricTimmyGun] = {
		id = RunItems.Ids.HistoricTimmyGun,
		entryId = "item:" .. RunItems.Ids.HistoricTimmyGun,
		displayName = "Historic Timmy Gun",
		description = "Continuously using your M1 ability increases your attack speed by 1-30% (+0.75-22.5% per stack) depending on how long you hold it for, using another ability or letting go of M1 puts this effect on a 7 second cooldown.",
		promptDescription = [[Continuously using your M1 ability increases your <font color="#F4A11A">attack speed</font> by <font color="#F4A11A">1-30%</font> <font color="#7A7A7A">(+0.75-22.5% per stack)</font> depending on how long you hold it for, using another ability or letting go of M1 puts this effect on a 7 second cooldown.]],
		dropModelName = "HistoricTimmyGun",
		viewportFrameName = "HistoricTimmyGunImageLabel",
		worldDropVisual = {
			renderMode = "legacySpecialMeshBackface",
			preferredChildName = "Historic ‘Timmy’ Gun",
		},
		timmy = {
			baseMinAttackSpeedBonus = 0.01,
			baseMaxAttackSpeedBonus = 0.30,
			stackMinAttackSpeedBonus = 0.0075,
			stackMaxAttackSpeedBonus = 0.225,
			fullRampDuration = 7.0,
			breakCooldown = 7.0,
			cadenceGraceMultiplier = 1.35,
		},
	},
	[RunItems.Ids.TeddyBloxpin] = {
		id = RunItems.Ids.TeddyBloxpin,
		entryId = "item:" .. RunItems.Ids.TeddyBloxpin,
		displayName = "Teddy Bloxpin",
		description = "Whenever you are attacked, you drop 'stuffing' within a 80 stud radius. Picking this up will grant you 5% overhealth and 20 Armor (+10 per stack) for 10 (+2s per stack) seconds.",
		promptDescription = [[Whenever you are attacked, you drop <font color="#F4A11A"><i>'stuffing'</i></font> within a 80 stud radius. Picking this up will grant you <font color="#17E317">5% overhealth</font> and <font color="#17E317">20 Armor</font> <font color="#7A7A7A">(+10 per stack)</font> for 10 <font color="#7A7A7A">(+2s per stack)</font> seconds.]],
		dropModelName = "TeddyBloxpin",
		viewportFrameName = "TeddyBloxpinImageLabel",
		worldDropVisual = {
			renderMode = "namedChild",
			preferredChildName = "Teddy Bloxpin",
		},
		teddy = {
			baseCooldown = 2.0,
			dropRadius = 80.0,
			stuffingModelPath = "ReplicatedStorage.ContentDrawer.ItemModels.CommonItems.Stuffing",
			stuffingLifetime = 12.0,
			stuffingPickupRadius = 10.0,
			baseOverhealthPercent = 0.05,
			baseArmor = 20,
			armorPerStack = 10,
			baseDuration = 10.0,
			durationPerStack = 2.0,
		},
	},
	[RunItems.Ids.RegenerationCoil] = {
		id = RunItems.Ids.RegenerationCoil,
		entryId = "item:" .. RunItems.Ids.RegenerationCoil,
		displayName = "Regeneration Coil",
		description = "Increases base health regeneration by +0.8 hp/s (+0.8 hp/s per stack) increased to +4 hp/s (+4 hp/s per stack) while out of combat.",
		promptDescription = [[Increases base <font color="#17E317">health regeneration</font> by <font color="#17E317">+0.8 hp/s</font> <font color="#7A7A7A">(+0.8 hp/s per stack)</font> increased to <font color="#17E317">+4 hp/s</font> <font color="#7A7A7A">(+4 hp/s per stack)</font> while out of combat.]],
		dropModelName = "RegenerationCoil",
		viewportFrameName = "RegenerationCoilViewportFrame",
		worldDropVisual = {
			renderMode = "namedChild",
			preferredChildName = "Regeneration Coil",
		},
		regenCoil = {
			baseFlatRegenPerStack = 0.8,
			outOfCombatFlatRegenPerStack = 4.0,
			outOfCombatDelay = 7.0,
		},
	},
	[RunItems.Ids.HealingPotion] = {
		id = RunItems.Ids.HealingPotion,
		entryId = "item:" .. RunItems.Ids.HealingPotion,
		displayName = "Healing Potion",
		description = "When you reach 45% or lower maximum health, drink a health potion, healing for 50 (+30 per stack) health on a 60 (-5% per stack) second cooldown.",
		promptDescription = [[When you reach <font color="#17E317">45%</font> or lower <font color="#17E317">maximum health</font>, drink a health potion, healing for <font color="#17E317">50</font> <font color="#7A7A7A">(+30 per stack)</font> <font color="#17E317">health</font> on a 60 <font color="#7A7A7A">(-5% per stack)</font> second cooldown.]],
		dropModelName = "HealingPotion",
		viewportFrameName = "HealingPotionViewportFrame",
		worldDropVisual = {
			renderMode = "legacySpecialMeshBackface",
			preferredChildName = "Healing Potion",
		},
		healingPotion = {
			triggerHealthThreshold = 0.45,
			baseHeal = 50,
			healPerAdditionalStack = 30,
			baseCooldown = 60.0,
			stackCooldownMultiplier = 0.95,
		},
	},
	[RunItems.Ids.LaserElectrocutor] = {
		id = RunItems.Ids.LaserElectrocutor,
		entryId = "item:" .. RunItems.Ids.LaserElectrocutor,
		displayName = "Laser Electrocutor",
		description = "7% (+5% per stack) chance to stun non-boss enemies on hit for 3 seconds.",
		promptDescription = [[7% <font color="#7A7A7A">(+5% per stack)</font> chance to <font color="#F4A11A">stun</font> non-boss enemies on hit for 3 seconds.]],
		dropModelName = "LaserElectrocutor",
		viewportFrameName = "LaserElectrocutorViewportFrame",
		laserElectrocutor = {
			baseProcChance = 0.07,
			procChancePerAdditionalStack = 0.05,
			stunDuration = 3.0,
		},
	},
	[RunItems.Ids.BuildersClubHardHat] = {
		id = RunItems.Ids.BuildersClubHardHat,
		entryId = "item:" .. RunItems.Ids.BuildersClubHardHat,
		displayName = "Builders Club Hard Hat",
		description = "Attacks deal -2 (-2 per stack) damage to you (Cannot drop below 1). Upon taking damage, gain tix equal to 7% of a small chest's cost.",
		promptDescription = [[Attacks deal <font color="#17E317">-2</font> <font color="#7A7A7A">(-2 per stack)</font> <font color="#17E317">damage</font> to you (Cannot drop below 1). Upon taking damage, gain <font color="#F4A11A">tix</font> equal to <font color="#17E317">7%</font> of a small chest's cost.]],
		dropModelName = "BuildersClubHardHat",
		viewportFrameName = "BuildersClubHardHatViewportFrame",
		buildersClubHardHat = {
			baseDamageReduction = 2,
			damageReductionPerAdditionalStack = 2,
			minimumAppliedDamage = 1,
			smallChestCost = 25,
			tixRefundFraction = 0.07,
		},
	},
	[RunItems.Ids.PepperoniPizza] = {
		id = RunItems.Ids.PepperoniPizza,
		entryId = "item:" .. RunItems.Ids.PepperoniPizza,
		displayName = "Pepperoni Pizza",
		description = "Decreases your secondary cooldown by -15% (-5% per stack) and increases the charges of your secondary ability by +1 (+1s per stack).",
		promptDescription = [[Decreases your secondary cooldown by -15% <font color="#7A7A7A">(-5% per stack)</font> and increases the <font color="#4A86FF">charges</font> of your <font color="#4A86FF">secondary ability</font> by +1 <font color="#7A7A7A">(+1s per stack)</font>.]],
		dropModelName = "PepperoniPizza",
		viewportFrameName = "PepperoniPizzaViewportFrame",
		pepperoniPizza = {
			baseSecondaryCooldownReduction = 0.15,
			secondaryCooldownReductionPerAdditionalStack = 0.05,
			chargesPerStack = 1,
			minimumCooldownMultiplier = 0.05,
		},
	},
	[RunItems.Ids.DeleteTool] = {
		id = RunItems.Ids.DeleteTool,
		entryId = "item:" .. RunItems.Ids.DeleteTool,
		displayName = "Delete Tool",
		description = "Your first attack inflicts 'First strike' dealing +80% (+80% per stack) damage.",
		promptDescription = [[Your first attack inflicts <font color="#F4A11A"><i>'First strike'</i></font> dealing <font color="#F4A11A">+80%</font> <font color="#7A7A7A">(+80% per stack)</font> <font color="#F4A11A">damage</font>.]],
		dropModelName = "DeleteTool",
		viewportFrameName = "DeleteToolViewportFrame",
		deleteTool = {
			triggerHealthThreshold = 0.95,
			baseBonusDamageMultiplier = 0.80,
			bonusDamagePerAdditionalStack = 0.80,
		},
	},
	[RunItems.Ids.AduriteCape] = {
		id = RunItems.Ids.AduriteCape,
		entryId = "item:" .. RunItems.Ids.AduriteCape,
		displayName = "Adurite Cape",
		description = "Increases the chance to 'Critically strike' enemies by 15% (+12% per stack), dealing 200% damage for that attack.",
		promptDescription = [[Increases the chance to <font color="#F4A11A">'Critically strike'</font> enemies by <font color="#F4A11A">15%</font> <font color="#7A7A7A">(+12% per stack)</font>, dealing <font color="#F4A11A">200% damage</font> for that attack.]],
		dropModelName = "AduriteCape",
		viewportFrameName = "AduriteCapeViewportFrame",
		aduriteCape = {
			baseCritChance = 0.15,
			critChancePerAdditionalStack = 0.12,
		},
	},
	[RunItems.Ids.SpeedCoil] = {
		id = RunItems.Ids.SpeedCoil,
		entryId = "item:" .. RunItems.Ids.SpeedCoil,
		displayName = "Speed Coil",
		description = "Increase movement speed by 15% (+15% per stack).",
		promptDescription = [[Increase <font color="#4A86FF">movement speed</font> by <font color="#4A86FF">15%</font> <font color="#7A7A7A">(+15% per stack)</font>.]],
		dropModelName = "SpeedCoil",
		viewportFrameName = "SpeedCoilViewportFrame",
		speedCoil = {
			moveSpeedBonusPerStack = 0.15,
		},
	},
	[RunItems.Ids.BloxyCola] = {
		id = RunItems.Ids.BloxyCola,
		entryId = "item:" .. RunItems.Ids.BloxyCola,
		displayName = "Bloxy Cola",
		description = "Increase attack speed by 15% (+15% per stack).",
		promptDescription = [[Increase <font color="#F4A11A">attack speed</font> by <font color="#F4A11A">15%</font> <font color="#7A7A7A">(+15% per stack)</font>.]],
		dropModelName = "BloxyCola",
		viewportFrameName = "BloxyColaViewportFrame",
		bloxyCola = {
			primaryAttackSpeedBonusPerStack = 0.15,
		},
	},
	[RunItems.Ids.Cheezburger] = {
		id = RunItems.Ids.Cheezburger,
		entryId = "item:" .. RunItems.Ids.Cheezburger,
		displayName = "Cheezburger",
		description = "Increase health by +20 and +5% total health (+20 and 4% per stack).",
		promptDescription = [[Increase <font color="#17E317">health</font> by <font color="#17E317">+20</font> and <font color="#17E317">+5% total health</font> <font color="#7A7A7A">(+20 and 4% per stack)</font>.]],
		dropModelName = "Cheezburger",
		viewportFrameName = "CheezburgerViewportFrame",
		cheezburger = {
			baseHealthFlat = 20,
			healthFlatPerAdditionalStack = 20,
			baseHealthMultiplier = 0.05,
			healthMultiplierPerAdditionalStack = 0.04,
		},
	},
	[RunItems.Ids.Bloxiade] = {
		id = RunItems.Ids.Bloxiade,
		entryId = "item:" .. RunItems.Ids.Bloxiade,
		displayName = "Bloxiade",
		description = "Increases attack speed by 10% (+10% per stack) and movement speed by 5% (+5% per stack).",
		promptDescription = [[Increases <font color="#F4A11A">attack speed</font> by <font color="#F4A11A">10%</font> <font color="#7A7A7A">(+10% per stack)</font> and <font color="#4A86FF">movement speed</font> by <font color="#4A86FF">5%</font> <font color="#7A7A7A">(+5% per stack)</font>.]],
		dropModelName = "Bloxiade",
		viewportFrameName = "BloxiadeViewportFrame",
		bloxiade = {
			primaryAttackSpeedBonusPerStack = 0.10,
			moveSpeedBonusPerStack = 0.05,
		},
	},
	[RunItems.Ids.Cake] = {
		id = RunItems.Ids.Cake,
		entryId = "item:" .. RunItems.Ids.Cake,
		displayName = "Cake",
		description = "Reduce the exp cost per level by -5% (-3% per stack) and gain +15% movement (+12% per stack) speed while sprinting.",
		promptDescription = [[Reduce the <font color="#4A86FF">exp</font> cost per level by <font color="#4A86FF">-5%</font> <font color="#7A7A7A">(-3% per stack)</font> and gain <font color="#4A86FF">+15%</font> <font color="#4A86FF">movement</font> <font color="#7A7A7A">(+12% per stack)</font> <font color="#4A86FF">speed</font> while <font color="#4A86FF">sprinting</font>.]],
		dropModelName = "Cake",
		viewportFrameName = "CakeViewportFrame",
		cake = {
			baseLevelExpCostReduction = 0.05,
			levelExpCostReductionPerAdditionalStack = 0.03,
			baseSprintMoveSpeedBonus = 0.15,
			sprintMoveSpeedBonusPerAdditionalStack = 0.12,
			minimumLevelExpCostMultiplier = 0.05,
		},
	},
	[RunItems.Ids.EnergySword] = {
		id = RunItems.Ids.EnergySword,
		entryId = "item:" .. RunItems.Ids.EnergySword,
		displayName = "Energy Sword",
		description = "Increase damage to enemies within 50 studs by 25% (+25% per stack).",
		promptDescription = [[Increase <font color="#F4A11A">damage</font> to enemies within <font color="#F4A11A">50 studs</font> by <font color="#F4A11A">25%</font> <font color="#7A7A7A">(+25% per stack)</font>.]],
		dropModelName = "EnergySword",
		viewportFrameName = "EnergySwordViewportFrame",
		energySword = {
			range = 50.0,
			baseCloseRangeDamageBonus = 0.25,
			closeRangeDamageBonusPerAdditionalStack = 0.25,
		},
	},
	[RunItems.Ids.Magic8Ball] = {
		id = RunItems.Ids.Magic8Ball,
		entryId = "item:" .. RunItems.Ids.Magic8Ball,
		displayName = "Magic 8 Ball",
		description = "15% (+15% per stack) chance to block and negate an incoming attack's damage.",
		promptDescription = [[<font color="#17E317">15%</font> <font color="#7A7A7A">(+15% per stack)</font> chance to <font color="#17E317">block</font> and negate an incoming attack's damage.]],
		dropModelName = "Magic8Ball",
		viewportFrameName = "Magic8BallViewportFrame",
		magic8Ball = {
			baseBlockChance = 0.15,
			blockChancePerAdditionalStack = 0.15,
		},
	},
	[RunItems.Ids.Apple] = {
		id = RunItems.Ids.Apple,
		entryId = "item:" .. RunItems.Ids.Apple,
		displayName = "Apple",
		description = "Overheal for 5 (+5 per stack) on kill.",
		promptDescription = [[<font color="#17E317">Overheal</font> for <font color="#17E317">5</font> <font color="#7A7A7A">(+5 per stack)</font> on kill.]],
		dropModelName = "Apple",
		viewportFrameName = "AppleViewportFrame",
		apple = {
			baseOverhealOnKill = 5,
			overhealOnKillPerAdditionalStack = 5,
		},
	},
}

function RunItems.get(itemId: string)
	return RunItems.Definitions[itemId]
end

function RunItems.getOrderedDefinitions(): {any}
	local ordered = table.create(#RunItems.Order)
	for _, itemId in ipairs(RunItems.Order) do
		local def = RunItems.Definitions[itemId]
		if def then
			table.insert(ordered, def)
		end
	end
	return ordered
end

return RunItems
