--!strict
-- Shared MovementBalance - client/server movement tuning values

return {
	AirMomentum = {
		enabled = true,
		mode = "target_state",
		writePhase = "PostSimulation",
		groundResetGraceSeconds = 0.08,
		groundCarryWindowSeconds = 0.1,
		overrideReleaseCarryWindowSeconds = 0.35,
		landingAssistSeconds = 0.08,
		landingAssistSpeedThreshold = 0.01,
		groundFrictionEnabled = false, -- deprecated: global ground slide path
		groundFrictionLinearDecel = 8.0,
		groundFrictionDrag = 1.0,
		groundFrictionMinSpeed = 1.0,
		groundOppositeBrakeAccel = 90.0,
		landingCarryEnabled = true,
		landingCarryActivationWalkspeedMultiplier = 1.15,
		landingCarryActivationMinSpeed = 22.0,
		landingCarryRecentAirborneWindow = 0.25,
		landingCarryMinDuration = 0.18,
		landingCarryMaxDuration = 0.70,
		landingCarryDurationRefSpeed = 90.0,
		landingCarryLinearDecel = 90.0,
		landingCarryDrag = 0.0, -- deprecated: use fixed decel only
		landingCarryTurnResponse = 9.0,
		landingCarryOppositeBrakeAccel = 135.0,
		landingCarryExitSpeed = 10.0,
		landingCarryPreserveWithSameInput = true,
		landingCarryDebugAttributes = false,
		oppositeDotThreshold = -0.2,
		oppositeBrakeAccel = 72,
		turnResponse = 7.5,
		turnSpeedLossPerSecond = 0.01,
		bhopLinearDecel = 0.0, -- 0 = auto derive from landingCarryLinearDecel / 3
		airDirectionalFightAccel = 260.0,
		airControlAccelToWalkSpeed = 42.0,
		airMisalignedBrakeAccel = 18.0,
		airMisalignedLossPerSecond = 1.25,
		noInputRetentionPerSecond = 0.9998,
		adoptExternalBoost = true,
		externalBoostAdoptThreshold = 1.0,
		softCapMinStart = 110,
		softCapWalkspeedMultiplier = 4.5,
		softCapHardMultiplier = 1.35,
		softCapDrag = 18.0,
		minControllableSpeed = 4.0,
		debugAttributes = false,
	},
}
