--!strict

return {
	id = "Oathkeeper",
	damage = 38,
	range = 1500,
	baseCooldown = 0.33,
	m2CastDuration = 0.60,
	m2FireDelay = 8 / 60,
	m2SharedLockout = 3.0,
	m2DamageMultiplier = 4.0,
	activeWalkWindow = 5,
	tracerLifetime = 0.6,
	tracerFadeDuration = 0.5,
	showPrimaryCooldown = false,
	primaryIconKey = "weapon:Oathkeeper",
	secondaryIconKey = "MagicBolt",
	usesCooldownMultiplier = true,
	usesDamageMultiplier = true,
	assetPaths = {
		weaponFolder = "ContentDrawer.WeaponModels.HandCannons.Oathkeeper",
		model = "OathkeeperModel",
		gripC0 = "GripC0",
		gripC1 = "GripC1",
		animations = {
			idle = "Animations.HandCannonIdle",
			walk = "Animations.HandCannonWalk",
			m1 = "Animations.HandCannonM1",
			m2 = "Animations.HandCannonChargedM2",
			reloadLoop = "Animations.HandCannonChargedReloadingLoop",
		},
		muzzlePart = "Barrel",
		muzzleFlash = "OathkeeperModel.Barrel.MuzzleFlash",
		tracer = "VFX.Tracer",
		m2Tracer = "VFX.M2Tracer",
		endpoint = "VFX.Endpoint",
		hitEffect = "VFX.Endpoint.HitEnd.HitEffect",
		hitEffectM2 = "VFX.Endpoint.HitEndM2",
	},
}
