--!strict
-- UpgradeDefs - Centralized config for the new rarity-based upgrade system

local UpgradeDefs = {}

UpgradeDefs.Rarities = {
	Common = {
		id = "Common",
		weight = 0.55,
		budget = 0.08,
		color = Color3.fromRGB(235, 235, 235),
		minStats = 1,
		maxStats = 1,
	},
	Rare = {
		id = "Rare",
		weight = 0.30,
		budget = 0.125,
		color = Color3.fromRGB(110, 170, 255),
		minStats = 1,
		maxStats = 2,
	},
	Epic = {
		id = "Epic",
		weight = 0.10,
		budget = 0.275,
		color = Color3.fromRGB(200, 120, 255),
		minStats = 2,
		maxStats = 3,
	},
	Legendary = {
		id = "Legendary",
		weight = 0.05,
		budget = 0.45,
		color = Color3.fromRGB(255, 190, 80),
		minStats = 3,
		maxStats = 3,
	},
}

UpgradeDefs.Luck = {
	minCommonWeight = 0.15,
	maxEpicMultiplier = 2.0,
	maxLegendaryMultiplier = 2.0,
}

UpgradeDefs.SoftCaps = {
	dangerousCap = 0.50,
	countMaxMultiplier = 5.0,
	curveK = 1.6,
}

UpgradeDefs.AbilityStats = {
	damage = {
		id = "damage",
		display = "Damage",
		field = "damage",
		min = 0.0625,
		max = 0.25,
		weight = 1.0,
		effect = "increase",
		kind = "percent",
	},
	projectileSpeed = {
		id = "projectileSpeed",
		display = "Projectile Speed",
		field = "projectileSpeed",
		min = 0.0425,
		max = 0.17,
		weight = 1.0,
		effect = "increase",
		kind = "percent",
	},
	attackSpeed = {
		id = "attackSpeed",
		display = "Cooldown",
		field = "pulseInterval",
		min = 0.025,
		max = 0.10,
		weight = 1.0,
		effect = "reduce",
		kind = "percent",
	},
	cooldownReduction = {
		id = "cooldownReduction",
		display = "Cooldown Reduction",
		field = "cooldown",
		min = 0.0425,
		max = 0.17,
		weight = 1.2,
		effect = "reduce",
		kind = "percent",
		softCap = UpgradeDefs.SoftCaps.dangerousCap,
	},
	projectileCount = {
		id = "projectileCount",
		display = "Projectile Count",
		field = "projectileCount",
		weight = 1.0,
		kind = "count",
	},
	shotAmount = {
		id = "shotAmount",
		display = "Shot Count",
		field = "shotAmount",
		weight = 1.0, -- same chance as projectile count
		increment = 0.5, -- half the value of projectile count upgrades
		legendaryIncrement = 1.0,
		kind = "count",
	},
}

UpgradeDefs.PassiveStats = {
	damage = {
		id = "damage",
		display = "Damage",
		field = "damageMultiplier",
		min = 0.0425,
		max = 0.17,
		weight = 1.0,
		effect = "increase",
	},
	critChance = {
		id = "critChance",
		display = "Crit Chance",
		field = "critChance",
		min = 0.02125,
		max = 0.085,
		weight = 1.2,
		effect = "increase",
		softCap = UpgradeDefs.SoftCaps.dangerousCap,
	},
	critDamage = {
		id = "critDamage",
		display = "Crit Damage",
		field = "critDamage",
		min = 0.075,
		max = 0.30,
		weight = 1.0,
		effect = "increase",
	},
	projectileCount = {
		id = "projectileCount",
		display = "Projectile Count",
		field = "projectileCount",
		weight = 1.0,
		kind = "count",
	},
	health = {
		id = "health",
		display = "Max Health",
		field = "healthMultiplier",
		min = 0.15,
		max = 0.60,
		weight = 1.0,
		effect = "increase",
		hidden = true, -- rolled via combined Health & Regen upgrade
	},
	regen = {
		id = "regen",
		display = "Regen",
		field = "regenMultiplier",
		min = 0.30,
		max = 1.20,
		weight = 1.0,
		effect = "increase",
		delayMin = 0.01, -- 1% faster regen delay per roll (min)
		delayMax = 0.08, -- 8% faster regen delay per roll (max)
		hidden = true, -- rolled via combined Health & Regen upgrade
	},
	healthRegen = {
		id = "healthRegen",
		display = "Health & Regen",
		kind = "paired",
		subStats = {"health", "regen", "armor"},
		weight = 1.0,
	},
	armor = {
		id = "armor",
		display = "Armor",
		field = "armorReduction",
		min = 0.02,
		max = 0.08,
		weight = 1.2,
		effect = "increase",
		softCap = 0.35,
		hidden = true, -- rolled via combined Health/Regen/Armor upgrade
	},
	lifesteal = {
		id = "lifesteal",
		display = "Lifesteal",
		field = "lifesteal",
		min = 0.0001,
		max = 0.0005,
		weight = 0.4,
		effect = "increase",
	},
	abilitySize = {
		id = "abilitySize",
		display = "Ability Size",
		field = "sizeMultiplier",
		min = 0.075,
		max = 0.30,
		weight = 1.0,
		effect = "increase",
	},
	cooldownReduction = {
		id = "cooldownReduction",
		display = "Cooldown Reduction",
		field = "cooldownMultiplier",
		min = 0.0425,
		max = 0.17,
		weight = 1.2,
		effect = "reduce",
		softCap = UpgradeDefs.SoftCaps.dangerousCap,
	},
	abilityDuration = {
		id = "abilityDuration",
		display = "Ability Duration",
		field = "durationMultiplier",
		min = 0.075,
		max = 0.30,
		weight = 1.0,
		effect = "increase",
	},
	penetration = {
		id = "penetration",
		display = "Penetration",
		field = "penetrationMultiplier",
		min = 0.125,
		max = 0.50,
		weight = 1.1,
		effect = "increase",
	},
	projectileBounce = {
		id = "projectileBounce",
		display = "Projectile Bounce",
		field = "projectileBounce",
		weight = 1.0,
		kind = "count",
	},
	moveSpeed = {
		id = "moveSpeed",
		display = "Movement Speed",
		field = "moveSpeedMultiplier",
		min = 0.0425,
		max = 0.17,
		weight = 1.0,
		effect = "increase",
		softCap = UpgradeDefs.SoftCaps.dangerousCap,
	},
	mobilityCooldown = {
		id = "mobilityCooldown",
		display = "Movement Cooldowns",
		field = "mobilityCooldownMultiplier",
		min = 0.0425,
		max = 0.17,
		weight = 1.2,
		effect = "reduce",
		softCap = UpgradeDefs.SoftCaps.dangerousCap,
	},
	doubleJumpPower = {
		id = "doubleJumpPower",
		display = "Double Jump Power",
		field = "mobilityVerticalMultiplier",
		min = 0.0425,
		max = 0.17,
		weight = 1.0,
		effect = "increase",
	},
	dashDistance = {
		id = "dashDistance",
		display = "Mobility Distance",
		field = "mobilityDistanceMultiplier",
		min = 0.0425,
		max = 0.17,
		weight = 1.0,
		effect = "increase",
	},
	grappleDistance = {
		id = "grappleDistance",
		display = "Grapple Distance",
		field = "grappleDistanceMultiplier",
		min = 0.0425,
		max = 0.17,
		weight = 1.0,
		effect = "increase",
	},
	luck = {
		id = "luck",
		display = "Luck",
		field = "luck",
		min = 0.075,
		max = 0.30,
		weight = 1.0,
		effect = "increase",
		softCap = UpgradeDefs.SoftCaps.dangerousCap,
	},
	expGain = {
		id = "expGain",
		display = "Exp Gain",
		field = "expMultiplier",
		min = 0.125,
		max = 0.50,
		weight = 1.0,
		effect = "increase",
	},
	pickupRange = {
		id = "pickupRange",
		display = "Pickup Range",
		field = "pickupRangeMultiplier",
		min = 0.125,
		max = 0.50,
		weight = 1.0,
		effect = "increase",
		hidden = true, -- driven by Exp Gain upgrade
	},
	powerupChance = {
		id = "powerupChance",
		display = "Powerup Chance",
		field = "powerupChance",
		min = 0.0025,
		max = 0.01,
		weight = 1.0,
		effect = "increase",
	},
}

return UpgradeDefs
